version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: roboshop
      MONGO_INITDB_ROOT_PASSWORD: Roboshop123
      MONGO_INITDB_DATABASE: master-data
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

#docker-compose up --build -d mongodb